name: Awaduya EC Report

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  send-report:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install packages
        run: npm install

      - name: Send report
        run: node index.js
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}